---
# - hosts: db
# - name: database assignment
#   ansible.builtin.import_playbook: ../static-assignments/uat-webservers.yml

# - hosts: nginx
# - name: nginx assignment
#   ansible.builtin.import_playbook: ../static-assignments/uat-webservers.yml

# - hosts: artifactory
# - name: artifactory assignment
#   ansible.builtin.import_playbook: ../static-assignments/uat-webservers.yml

- hosts: todo
- name: Deploying the PHP Applicaion to Dev Enviroment
  import: ../static-assignments/php.yml